### ISSUE TITLE
-mockPeripheral:readValueForCharacteristic: method caches char value

### ISSUE THREAD

**Issue by cpatterson-lilly** [Raizlabs/RZBluetooth#52]
Just a question here related to using the mock objects for unit testing. 

I see that the method `RZBSimulatedConnection -mockPeripheral:readValueForCharacteristic:` will never call through to any `readHandlers` set up on the `RZBSimulatedDevice` object once a characteristic value has been set (i.e. once `if (characteristic.value == nil)` is false).

Is this how a real Core Bluetooth connection works? 

I know that when you use a `nil` characteristic value when initializing a `CBMutableCharacteristic`, the Apple docs say:

> If <i>nil</i>, the value will be dynamic and requested on-demand.

...but it doesn't specify what happens the _second_ time a central reads its value.

I'd like my mock read handlers to be called every time the characteristic is read during unit testing.

**Comment by KingOfBrian** [comment]
Yea, there's definitely something off here. If a service is *created* with a value that value should always be returned, but if value is nil and a callback supplies a value, subsequent reads should also trigger the callback. We need to track the "dynamic read" characteristic UUIDs in `addService` and `removeService`. If there was a set of `dynamicCharacteristicUUIDs` in the simulated connection, `addService` and `removeService` can add / remove all of the child characteristic UUIDs, and the read simulation can check that state instead of `value == nil`.

I won't be able to implement this any time too soon, but would love a PR !
